networks:
  default: {}
  proxynet:
    external:
      name: proxy_network
services:
  client:
    build:
      context: /home/giacomo/Documents/Lavoro/GILabs/laravel-vue-nginx-compose/client
      dockerfile: Dockerfile
    networks:
      default: null
    volumes:
    - ./client:/app
  db:
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: test_db_password
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_USER: root
      MYSQL_USER: test
    healthcheck:
      retries: 10
      test:
      - CMD
      - mysqladmin
      - ping
      - -h
      - localhost
      - -u
      - test
      - -ptest_db_password
      timeout: 20s
    image: mysql:5.7
    networks:
      default: null
    ports:
    - 7000:3306/tcp
    volumes:
    - database:/var/lib/mysql:rw
  server:
    build:
      context: /home/giacomo/Documents/Lavoro/GILabs/laravel-vue-nginx-compose/server
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: test
      DB_PASSWORD: test_db_password
      DB_PORT: '3306'
      DB_USER: test
    links:
    - db:db
    networks:
      default: null
    volumes:
    - ./server:/var/www:rw
  web:
    build:
      context: /home/giacomo/Documents/Lavoro/GILabs/laravel-vue-nginx-compose/web
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: test.local
      VIRTUAL_PORT: '8080'
    links:
    - client
    - server
    networks:
      default: null
      proxynet: null
    volumes:
      - ./web/nginx.dev.conf:/etc/nginx/nginx.conf:rw
version: '3.0'
volumes:
  database:
    driver: local
