import Vue from "vue";

import DateRangePicker from "vue2-daterange-picker";
import ImageUploader from "@/components/ImageUploader";
import Loading from "@/components/Loading.vue";
import Chart from "@/components/Chart";
import AwesomeTable from "@/components/AwesomeTable";
import SectionTitle from "@/components/SectionTitle";
import ColorSwatch from "@/components/ColorSwatch";
import InsightCard from "@/components/InsightCard";
import UserDetail from "@/components/UserDetail.vue";
import CountryFlag from "vue-country-flag";
import Avatar from "@/components/Avatar.vue";
import HorizontalPieChart from "@/components/HorizontalPieChart.vue";
import EngagementDetail from "@/components/EngagementDetail.vue";
import BlurImage from "@/components/BlurImage.vue";
import SvgIcon from "@/components/SvgIcon.vue";
import PageError from "@/components/PageError.vue";
import ErrorBoundary from "@/components/ErrorBoundary.vue";
import UserSyncManager from "@/components/UserSyncManager.vue";
import InsightsSet from "@/components/InsightsSet.vue";

Vue.component("image-uploader", ImageUploader);
Vue.component("loading", Loading);
Vue.component("chart", Chart);
Vue.component("awesome-table", AwesomeTable);
Vue.component("section-title", SectionTitle);
Vue.component("color-swatch", ColorSwatch);
Vue.component("insight-card", InsightCard);
Vue.component("country-flag", CountryFlag);
Vue.component("user-detail", UserDetail);
Vue.component("avatar", Avatar);
Vue.component("horizontal-pie-chart", HorizontalPieChart);
Vue.component("engagement-detail", EngagementDetail);
Vue.component("aw-datepicker", DateRangePicker);
Vue.component("blr-image", BlurImage);
Vue.component("svg-icon", SvgIcon);
Vue.component("page-error", PageError);
Vue.component("user-sync-manager", UserSyncManager);
Vue.component("error-boundary", ErrorBoundary);
Vue.component("insights-set", InsightsSet);
